WSL finetuning
plone/documentation pull request #1100
Opened 2019-10-29 11:25 UTC by jensens

WSL chapter:
- remove dup section 
- minor ReST fixes
- finetuning in formatting

Windows section: mention and link WSL chapter

2019-11-04 16:46 UTC, idgserpro commented on manage/installing/installation.rst
> +An alternative to directly running Plone 5 on Winodws is to use the official Windows Subsystem Linux (WSL, formerly also known as LXSS).
There's a small typo here, `Winodws` instead of `Windows`.

2019-11-04 16:51 UTC, stevepiercy requested changes
Minor typo and grammar fixes.

2019-11-04 16:51 UTC, stevepiercy commented on manage/installing/installation.rst
> +An alternative to directly running Plone 5 on Winodws is to use the official Windows Subsystem Linux (WSL, formerly also known as LXSS).
```suggestion
An alternative to directly running Plone 5 on Windows is to use the official Windows Subsystem Linux (WSL, formerly also known as LXSS).
```

2019-11-04 16:51 UTC, stevepiercy commented on manage/installing/installation_windows10_wsl.rst
> +Therefor, the programm Windows PowerShell has to be launched (as administrator! - right-click the application and choose :guilabel:`launch as admin`).
```suggestion
Therefor, the program Windows PowerShell has to be launched (as administrator! - right-click the application and choose :guilabel:`launch as admin`).
```

2019-11-04 16:51 UTC, stevepiercy commented on manage/installing/installation_windows10_wsl.rst
> +I.e. create a folder in Windows ``C:\Plone-Projects``.
```suggestion
Create a folder in Windows ``C:\Plone-Projects``.
```

2019-11-05 17:49 UTC, stevepiercy requested changes
Thanks for the changes. I found a couple more upon more careful review.

2019-11-05 17:49 UTC, stevepiercy commented on manage/installing/installation_windows10_wsl.rst
> +Therefor, the program Windows PowerShell has to be launched (as administrator! - right-click the application and choose :guilabel:`launch as admin`).
```suggestion
Therefore the program Windows PowerShell has to be launched (as administrator! - right-click the application and choose :guilabel:`launch as admin`).
```

2019-11-05 17:49 UTC, stevepiercy commented on manage/installing/installation_windows10_wsl.rst
>  Before installing the shell to later configure in, the first thing to do is to enable the optional feature for a subsystem on windows.
```suggestion
Before installing the shell for configuration, first enable the optional feature for a subsystem on Windows.
```

2019-11-06 10:19 UTC, merged