Enable logging in unit-tests: Clarify and simplify the example and code
plone/documentation pull request #1103
Opened 2019-11-06 12:39 UTC by thet

Improves: Section: "Setting log level in unit tests"

Changes proposed in this pull request:

- Simplify the example code by not depending on ``Products.CMFPlone.log``

- Make the problem clearer (log stdout logging at all)

- Make it clearer how to use.

I did not change the heading although I think "Enable logging to stdout in unit tests" would be better. But that would break existing references to this section.

2019-11-06 16:19 UTC, stevepiercy requested changes
Couple of grammar fixes, and use a language name and `code-block` to avoid ambiguity.

2019-11-06 16:19 UTC, stevepiercy commented on develop/testing/unit_testing.rst
> +To enable logging to stdout do add the following to your test setup code::
```suggestion
To enable logging to stdout, add the following to your test setup code.

.. code-block:: python
```

2019-11-06 16:19 UTC, stevepiercy commented on develop/testing/unit_testing.rst
> +You may also want to set the loglevel from ``INFO`` to ``DEBUG``.
```suggestion
To reveal these messages, change the log level from ``INFO`` to ``DEBUG``.
```

2019-11-06 16:22 UTC, stevepiercy commented
> I did not change the heading although I think "Enable logging to stdout in unit tests" would be better. But that would break existing references to this section.

You could refactor. If you go that route, the preferred method is using an arbitrary cross-reference and label.

```
.. _my-fancy-label:

Heading
-------

:ref:`my-fancy-label`
```

2019-11-06 17:41 UTC, jensens approved these changes
+1 for merge after the small glitches found by @stevepiercy are in.
If you think the title should improve, then do it. `grep` is your friend.

2021-11-12 12:51 UTC, spereverde approved these changes

2021-11-12 12:51 UTC, merged