image handling: add cleanup note
plone/documentation pull request #1196
Opened 2022-03-09 13:03 UTC by MrTango

2022-03-09 13:03 UTC, mister-roboto commented
@MrTango thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-03-09 13:52 UTC, stevepiercy requested changes
Question on .gitignore item.
One sentence per line.
Spell out "hours".

2022-03-09 13:52 UTC, stevepiercy commented on .gitignore
> +/lib64
This is not symlinked from submodule. Is this from a virtual environment on arch64? If so, then it should go under the `#Dependencies` heading.

2022-03-09 13:52 UTC, stevepiercy commented on docs/classic-ui/images.md
> +This changes the URL and forces either the browser, or a cache proxy such as Varnish, to fetch it again. When a scale has changed, the old stored entry in the annotation will be deleted after 24h.
```suggestion
This changes the URL and forces either the browser, or a cache proxy such as Varnish, to fetch it again.
When a scale has changed, the old stored entry in the annotation will be deleted after 24 hours.
```

2022-03-09 22:11 UTC, stevepiercy requested changes

2022-03-09 22:11 UTC, stevepiercy commented on docs/classic-ui/images.md
> +If one changes an image which is used in multiple pages, the updated versions will only be shown after a restart of the Plone instance, saving the pages again or after 24h.
Use the Oxford comma, and spell out hours.

```suggestion
If one changes an image which is used in multiple pages, the updated versions will only be shown after a restart of the Plone instance, saving the pages again, or after 24 hours.
```

2022-03-14 22:17 UTC, mauritsvanrees approved these changes

2022-03-15 13:50 UTC, stevepiercy approved these changes

2022-03-15 13:52 UTC, stevepiercy commented
I think the failing CI is because we need to update submodule/volto to point to its master branch. I'm going to merge this, and if it doesn't build, I will update the submodule.

2022-03-15 13:53 UTC, merged