Update icons chapter
plone/documentation pull request #1203
Opened 2022-03-16 20:42 UTC by MrTango

2022-03-16 20:42 UTC, mister-roboto commented
@MrTango thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-03-17 12:17 UTC, stevepiercy requested changes
Thank you for the improvements. Mostly English grammar, and the one sentence per line thing.

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +This provides an option to customize the contenttype and Plone UI icons by overriding icons via XML. Plone ships with the following icon registrations by default.
When used in narrative text, "contenttype" should be two words, "content type". Else it should be an inline literal or in a code-block.

Also please use one line per sentence.

```suggestion
This provides an option to customize the content type and Plone UI icons by overriding icons via XML.
Plone ships with the following icon registrations by default.
```

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +The icons above are made available as plone resources.
```suggestion
The icons above are made available as Plone resources.
```

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +For example, the lightning icon's resource path is `++plone++bootstrap-icons/lightning.svg`. One could register another icon set under a new name, for example `++plone++fontawesome-icons` and overrid
```suggestion
For example, the lightning icon's resource path is `++plone++bootstrap-icons/lightning.svg`.
One could register another icon set under a new name, for example `++plone++fontawesome-icons`, and override the registrations above to use them.
```

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +For example we have an icon registered under the name `plone.icon.plone-copy` in https://github.com/plone/plone.staticresources/blob/master/src/plone/staticresources/profiles/default/registry/icons_p
```suggestion
For example we have an icon registered under the name `plone.icon.plone-copy` in https://github.com/plone/plone.staticresources/blob/master/src/plone/staticresources/profiles/default/registry/icons_plone.xml which points to the bootstrap `clipboard-plus` icon `++plone++bootstrap-icons/clipboard-plus.svg`.
```

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +```{note}
```suggestion
```{todo}
```

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +## Iconresolver
```suggestion
## Icon resolver
```

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +The iconresolver take's an icon name (without the `plone.icon.` prefix) like `plone-copy` or `align-center` and resolves it to an actual icon.
```suggestion
The icon resolver takes an icon name, such as `plone-copy` or `align-center` (without the `plone.icon.` prefix), and resolves it to an actual icon.
```

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +```
````suggestion
```console
````

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +http://localhost:8080/Plone/@@iconresolver/align-center
Combine this code block with the previous one.

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +It can be used via URL or via Python as shown below.
This is not clear. What is "it"? The icon resolver or the URL?

Which section below? Please name the specific section or use a link, e.g.:

```
...as described in the section {ref}`classic-ui-icons-iconresolver-get-icon-url-label`.
```

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +The `url` method of `@@iconresolver` view returns the actual url to the SVG icon. The iconresolver view is globally available in templates under the name `icons`.
```suggestion
The `url` method of the `@@iconresolver` view returns the actual URL to the SVG icon.
The icon resolver view is globally available in templates under the name `icons`.
```

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
>  `tag_class` and `tag_alt` is used to pass in custom classes and an `alt` text.
```suggestion
`tag_class` and `tag_alt` are used to pass in custom classes and an `alt` text.
```

2022-03-17 12:17 UTC, stevepiercy commented on docs/classic-ui/icons.md
> +[Mockup](https://github.com/plone/mockup) provides an iconResolver function, defined in core/utils.js,  which does this the same way and has a fallback for demo and testing.
```suggestion
[Mockup](https://github.com/plone/mockup) provides an `iconResolver` function, defined in `core/utils.js`,  which does this the same way and has a fallback for demo and testing.
```

2022-03-21 08:04 UTC, jensens reviewed
Looks like this chapter still needs some love from @santonelli or me.

2022-03-21 08:04 UTC, jensens commented on docs/classic-ui/icons.md
> +For example, the lightning icon's resource path is `++plone++bootstrap-icons/lightning.svg`.
```suggestion
For example, the icon registered as `lightning` (in XML with prefix full name is `plone.icon.lighting`) resource path is `++plone++bootstrap-icons/lightning.svg`.
```

2022-04-05 08:06 UTC, stevepiercy commented
@jensens @santonelli when you have a moment, would you please share the ❤️  on this PR?

2022-04-07 09:21 UTC, merged