Fix Github button 'suggest edit'  (at least for non-submodule docs)
plone/documentation pull request #1221
Opened 2022-04-06 09:04 UTC by ksuess

2022-04-06 09:04 UTC, mister-roboto commented
@ksuess thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-04-06 09:05 UTC, stevepiercy approved these changes

2022-04-06 09:57 UTC, ksuess commented
Fixing the "suggest edit" link for submodule docs would mean a massive interference in sphinx-book-theme https://github.com/executablebooks/sphinx-book-theme/blob/526956165f3fda3e5faaf53ffc39081715702f6d/src/sphinx_book_theme/header_buttons/__init__.py#L94-L102

I tend to just hide the link for submodule pages (Volto, plone.restapi, plone.api) via CSS.

2022-04-06 10:56 UTC, stevepiercy commented
What do you think of using JavaScript to rewrite the URL for non-main documentation to https://6.dev-docs.plone.org/contributing/index.html ?

Actually, I think I would prefer to use that link site-wide than "suggest an edit" for each page. I don't want to raise expectations of people making "drive by" pull requests without signing the Plone Contributor Agreement. This would direct them toward the authoritative method to submit a PR.

2022-04-06 11:27 UTC, ksuess commented
> What do you think of using JavaScript to rewrite the URL for non-main documentation to https://6.dev-docs.plone.org/contributing/index.html ?
> 
> Actually, I think I would prefer to use that link site-wide than "suggest an edit" for each page. I don't want to raise expectations of people making "drive by" pull requests without signing the Plone Contributor Agreement. This would direct them toward the authoritative method to submit a PR.

Yes, I completly aggree. 👍

2022-04-06 21:39 UTC, stevepiercy requested changes

2022-04-06 21:39 UTC, stevepiercy commented on docs/conf.py
>      "use_edit_page_button": True,
```suggestion
    "use_edit_page_button": False,
```

Then in a template, we can hard code a link to https://6.dev-docs.plone.org/contributing/index.html

2022-04-07 07:35 UTC, stevepiercy commented
See https://github.com/plone/documentation/issues/1211

2022-04-13 06:29 UTC, MrTango commented
> What do you think of using JavaScript to rewrite the URL for non-main documentation to https://6.dev-docs.plone.org/contributing/index.html ?
> 
> Actually, I think I would prefer to use that link site-wide than "suggest an edit" for each page. I don't want to raise expectations of people making "drive by" pull requests without signing the Plone Contributor Agreement. This would direct them toward the authoritative method to submit a PR.

For the docs it is not required to sign the controbutor aggrement as far as i know.

2022-04-13 09:25 UTC, stevepiercy commented
> For the docs it is not required to sign the controbutor aggrement as far as i know.

See https://6.dev-docs.plone.org/contributing/index.html#granting-permission-to-publish as established by https://docs.plone.org/about/license.html.

> With that in mind, i would prefer a direct link to update docs, not just to a document.

I would, too. However with the complexity of importing submodules from three other repos, this is not easy.

2022-09-06 06:22 UTC, ksuess commented
GitHub link for "suggest edit" overridden for this repo: Impede drive-by edits by linking chapter on how to contribute. Fixed in https://github.com/plone/documentation/pull/1292

2022-09-06 06:22 UTC, closed without merging