Module Federation Documentation.
plone/documentation pull request #1253
Opened 2022-05-16 09:11 UTC by thet

2022-05-17 17:02 UTC, reinhardt commented
See also https://github.com/Patternslib/Patterns/blob/master/docs/developer/module-federation.md

2022-06-01 08:14 UTC, ksuess requested changes

2022-06-01 08:14 UTC, ksuess commented on docs/classic-ui/module-federation.md
> +
```suggestion
This instruction is for you if you created an add-on with a Mockup pattern and you want to include the respective Javascript code in your theme code.
```

2022-06-01 08:21 UTC, reinhardt commented
Thanks for the suggestion! I'm actually starting to doubt whether it makes sense to have a separate chapter on module federation. With https://github.com/plone/bobtemplates.plone/pull/507 you will get it for free in the future when creating a pattern with plonecli/bobtemplates. There should probably be documentation how to customize a pattern, including a sentence that mentions module federation, but maybe not a full explanation.

2022-06-01 08:33 UTC, ksuess commented
> Thanks for the suggestion! I'm actually starting to doubt whether it makes sense to have a separate chapter on module federation. With [plone/bobtemplates.plone#507](https://github.com/plone/bobtemplates.plone/pull/507) you will get it for free in the future when creating a pattern with plonecli/bobtemplates. There should probably be documentation how to customize a pattern, including a sentence that mentions module federation, but maybe not a full explanation.

Module federation is independent of Mockup patterns, but is the way JS bundles are composed the Plone 6 way, am I correct?

So, will this draft also be an instruction for "I have a Plone 5 add-on with some arbitrary Javascript code, not necessary a Mockup pattern, and I want to know, how I to lift this Plone 5 add-on to Plone 6"?

2022-06-01 11:12 UTC, reinhardt commented
Yes and no... Probably @thet can explain that better?

2022-06-13 10:47 UTC, stevepiercy requested changes

2022-06-13 10:47 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +This instruction is for you if you created an add-on with a Mockup pattern and you want to include the respective Javascript code in your theme code.
```suggestion
This instruction is for you if you created an add-on with a Mockup pattern and you want to include the respective JavaScript code in your theme code.
```

2022-07-19 08:16 UTC, stevepiercy requested changes

2022-07-19 08:16 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +## Special case: global modules ``jQuery`` and ``Bootstrap``
Markdown uses single backticks for inline literals.

```suggestion
## Special case: global modules `jQuery` and `Bootstrap`
```

2022-07-19 08:16 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +the modules ``jQuery`` and ``Bootstrap`` are stored in the  global ``window`` namespace.
```suggestion
the modules `jQuery` and `Bootstrap` are stored in the  global `window` namespace.
```

2022-07-19 08:16 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +```
Add the lexer.

````suggestion
```js
````

2022-07-19 09:10 UTC, stevepiercy requested changes
In this review, I cover the entire document to date.

It's looking good. Thank you!

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +## Introduction
This heading is unnecessary.

```suggestion
```

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +For a general introduction see: https://webpack.js.org/concepts/module-federation/
I would like to move this to the end of this section, just before the next subheading of "Using module federation".

Let's convert it to a `seealso` directive.

````suggestion
```{seealso}
Webpack's documentation on [Module Federation](https://webpack.js.org/concepts/module-federation/).
```
````

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +Module Federation allows to share dependencies between bundles.
```suggestion
Module Federation allows sharing of dependencies between bundles.
```

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +There is a host bundle - in the fictional example above our bundle "A".
```suggestion
There is a host bundle, as in the fictional example above, our bundle A.
```

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +Addons can add bundles called "remotes" which are initialized for module federation by the host bundle.
```suggestion
Add-ons can add bundles called "remotes" which are initialized for module federation by the host bundle.
```

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +This instruction is for you if you created an add-on with a Mockup pattern and you want to include the respective JavaScript code in your theme code.
```suggestion
The following instructions are for you if you created an add-on with a Mockup pattern and you want to include the respective JavaScript code in your theme code.
```

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +Starting with the webpack configuration that you get when creating a barceloneta theme package via [plonecli][1], add the following:
```suggestion
Starting with the webpack configuration that you get when creating a Barceloneta theme package via [plonecli][1], add the following:
```

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +- Add the module federation plugin in webpack.config.js. There is a configuration factory `mf_config` which you can use for that. Add the following line near the top of the file:
```suggestion
Next add the module federation plugin in `webpack.config.js`.
There is a configuration factory `mf_config` which you can use for that.
Add the following line near the top of the file:
```

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +```
If you ignore the previous suggestion, code blocks within list items should be indented to align with the first letter of the list item.

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +- Create a new entry point `index.js` which only imports the normal entry point.
```suggestion
Create a new entry point `index.js` which only imports the normal entry point.
```

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +- Create a new entry point `index.js` which only imports the normal entry point.
With only two list items, I would remove the `-`. This also avoids the requirement of indenting everything to align with the list item.

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +Replace `myaddon-remote.min.js` with the file name you want to use for your remote bundle. Replace `myaddon.min` with the corresponding key in `config.entry` that points to your `index.js`.
One sentence per line.

```suggestion
Replace `myaddon-remote.min.js` with the file name you want to use for your remote bundle.
Replace `myaddon.min` with the corresponding key in `config.entry` that points to your `index.js`.
```

2022-07-19 09:10 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +In order to preserve compatibility with older addons and JavaScript implementations,
```suggestion
In order to preserve compatibility with older add-ons and JavaScript implementations,
```

2022-07-21 02:49 UTC, stevepiercy requested changes
One minor fix, and this is good to go.

If there are more things that need to be added, I would suggest adding an outline of those items at the least. Then we can fill in details.

Thank you!

2022-07-21 02:49 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +```
Please move the above part after the content for this section, after "Add-ons can add bundles called "remotes" which are initialized for module federation by the host bundle." and before "## Using module federation". We need an introduction before showing a link to an external site.

2022-07-21 06:11 UTC, ksuess commented
Please include "classic-ui/module-federation" in naviagation.

2022-07-21 07:12 UTC, ksuess requested changes
I have questions. This is how to get the custom pattern (js pattern code) of my add-on up and running. What about other js code. For example old jquery code. Would it maybe make sense to provide information about this traditional stuff also here, or would that go in another chapter?

2022-07-21 07:12 UTC, ksuess commented on docs/classic-ui/module-federation.md
> +The following instructions are for you if you created an add-on with a Mockup pattern and you want to include the respective JavaScript code in your theme code.
I landed here and want to know how to write a Mockup pattern. Where can I find instructions? Link?

2022-07-21 07:12 UTC, ksuess commented on docs/classic-ui/module-federation.md
> +Starting with the webpack configuration that you get when creating a Barceloneta theme package via [plonecli][1], add the following:
If I create a new addon and add a Barceloneta theme via plonecli, I do not see a webpack configuration.
plonecli 2.2
bobtemplates.plone: 6.0b12
```
plonecli create addon abc.mytheme
plonecli add theme_barceloneta
```

2022-07-21 07:12 UTC, ksuess commented on docs/classic-ui/module-federation.md
> +Create a new entry point `index.js` which only imports the normal entry point.
Where do I have to create this file?

2022-07-21 07:12 UTC, ksuess commented on docs/classic-ui/module-federation.md
> +Replace `myaddon-remote.min.js` with the file name you want to use for your remote bundle.
Is `myaddon-remote.min.js` generated? How is it generated and where do I have to place the source file?

2022-07-21 07:12 UTC, ksuess commented on docs/classic-ui/module-federation.md
> +Replace `myaddon-remote.min.js` with the file name you want to use for your remote bundle.
What means remote in this context and what would be a non-remote? I thought this instruction is about applying the js code of my addon

2022-07-21 07:12 UTC, ksuess commented on docs/classic-ui/module-federation.md
> +Replace `myaddon.min` with the corresponding key in `config.entry` that points to your `index.js`.
```suggestion
Replace the key of `config.entry` that points to your `index.js` with the name of your add-on.
```

2022-07-21 07:12 UTC, ksuess commented on docs/classic-ui/module-federation.md
> +
Do I need to run a compile script or is a restart of Plone enough?

2022-07-21 21:59 UTC, thet commented
@ksuess that doc here was not really meant to get you started from scratch. It's more about how to configure module federation.
But I agree - we need a how to start document, also a bobtemplates integration (started but here: https://github.com/plone/bobtemplates.plone/pull/507 but not finished yet).
Not sure if these docs should be extended for a full start-from-scratch, or should it?

Btw. the https://github.com/Patternslib/pat-PATTERN_TEMPLATE is IMO a good patterns generator and a perfect starting point.
However, it does not provide a plone integration (registering of resources, etc) - this is what the bobtemplates PR‌ is about.

@petschki I added some fixes for the recent webpack.mf.js changes plus some references to full, working examples.

Btw. I'm on vacation the next two weeks, so don't expect any updates from me.. :)

2022-07-22 06:46 UTC, stevepiercy requested changes
A couple of English syntax improvements, using shorter sentences, and an optional suggestion for link syntax.

2022-07-22 06:46 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +Potentially these are the ones from Patternslib, Mockup and your own dependencies.
When a term is first introduced on a page, we must either define it or provide a reference to its meaning, either with a Glossary entry or a link to an external website where it is defined. Please amend the link to whatever is preferred.

I also noticed that I overlooked that Mockup lacks a definition or reference when it is was first introduced, so that should be done above as well.

```suggestion
Potentially these are the ones from [Patternslib](https://github.com/Patternslib/pat-PATTERN_TEMPLATE), Mockup, and your own dependencies.
```

2022-07-22 06:46 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +Replace the name `myaddon` with your addon bundle's name (any unique name will do...),
```suggestion
Replace the name `myaddon` with your add-on bundle's unique name.
```

2022-07-22 06:46 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +replace the filename `myaddon-remote.min.js` with the file name you want to use for your remote bundle,
```suggestion
Replace the filename `myaddon-remote.min.js` with the file name you want to use for your remote bundle.
```

2022-07-22 06:46 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +and replace `myaddon.min` with the corresponding key in `config.entry` that points to your `index.js`.
```suggestion
Finally replace `myaddon.min` with the corresponding key in `config.entry` that points to your `index.js`.
```

2022-07-22 06:46 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +For a full but simple example, see the Patterns generator [pat-PATTERN-TEMPLATE][2] or any other Pattern addon in the patternslib GitHub organisation.
```suggestion
For a full but simple example, see the Patterns generator [pat-PATTERN-TEMPLATE][2] or any other Pattern add-on in the [patternslib GitHub organization](https://github.com/patternslib/).
```

2022-07-22 06:46 UTC, stevepiercy commented on docs/classic-ui/module-federation.md
> +For a complex example with Mockup integration see [plone.app.mosaic][3] and [Mockup][4] itself.
This suggestion is optional. In general, I prefer to keep the URL next to its label as in `[label](https://url.com/path)`, instead of this reference style. They both render the same for readers. But for authors it has advantages:

- Simpler syntax.
- It associates the label with the link directly, instead of requiring the author to scroll down to reference it.
- When a link is broken, `linkcheck` and `linkcheckbroken` refer to the line of the label, not the URL, in the error, so you would see something like `classic-ui/module-federation: line   31) broken    https://pypi.org/project/plonecli-404/ - 404 Client Error: Not Found for url: https://pypi.org/project/plonecli-404/`
- Preferred by most authors.

Perhaps that style was carried over from the dogma of keeping line lengths to 80 characters. In narrative documentation, line length does not matter. It is not code and most editors can soft wrap long lines of text these days.

2022-07-22 08:16 UTC, ksuess commented
> @ksuess that doc here was not really meant to get you started from scratch. It's more about how to configure module federation. But I agree - we need a how to start document, also a bobtemplates integration (started but here: [plone/bobtemplates.plone#507](https://github.com/plone/bobtemplates.plone/pull/507) but not finished yet). Not sure if these docs should be extended for a full start-from-scratch, or should it?
> 
> Btw. the https://github.com/Patternslib/pat-PATTERN_TEMPLATE is IMO a good patterns generator and a perfect starting point. However, it does not provide a plone integration (registering of resources, etc) - this is what the bobtemplates PR‌ is about.
> 
> @petschki I added some fixes for the recent webpack.mf.js changes plus some references to full, working examples.
> 
> Btw. I'm on vacation the next two weeks, so don't expect any updates from me.. :)

Ah, OK, then this is chapter is focused on Module Federation. And it assumes knowledge on how to work with static resources in general, how to add static resources (js, css) to a custom theme (based on Barceloneta or not). 

Then the questions of a theme / add-on creator should be answered in a general chapter on static resources, which indeed already exists! After your comment, I found it: https://6.dev-docs.plone.org/classic-ui/theming/from-scratch.html#theme . The chapter title "Plone Classic UI Theming based on Barceloneta" should probable read something like "Plone Classic UI Theming **independent** of Barceloneta".
I'll mark my former imaginary theme creator questions as resolved and find a way to add them to  https://6.dev-docs.plone.org/classic-ui/theming/from-scratch.html#theme if appropriate.

2022-07-22 09:41 UTC, ksuess commented on docs/classic-ui/module-federation.md
> +The following instructions are for you if you created an add-on with a Mockup pattern and you want to include the respective JavaScript code in your theme code.
This imaginary theme/add-on creator question and the ones below can be answered in other chapters. 
If you read this and think this is your topic: Feel free to take over PR https://github.com/plone/documentation/pull/1275

2022-07-22 11:33 UTC, jensens commented
I read the instructions and I am a bit clueless. Could we have some very minimal but complete and working example?

2022-08-03 15:39 UTC, MrTango commented
> Then the questions of a theme / add-on creator should be answered in a general chapter on static resources, which indeed already exists! After your comment, I found it: https://6.dev-docs.plone.org/classic-ui/theming/from-scratch.html#theme . The chapter title "Plone Classic UI Theming based on Barceloneta" should probable read something like "Plone Classic UI Theming **independent** of Barceloneta".

`from-scratch` here stays for no Diazo, only templates overrides vs `diazo`.
In the docs there is not much for theming sofar, but the training has already quite some infos, but they need an update before the conference.

like in the training: [Create a Theme from scratch](https://training.plone.org/5/theming/theme_scratch.html) vs [Create a theme based on Diazo](https://training.plone.org/5/theming/theme_diazo.html#)

2024-04-28 23:10 UTC, stevepiercy commented
@thet @reinhardt @ksuess @jensens @MrTango I updated the base branch and tidied up the MyST and English grammar and syntax. I'd appreciate your collaboration to get this PR finished and deployed to the documentation. Thank you!

2024-04-29 07:49 UTC, jensens commented
Overall this looks good, what is missing?

2024-07-01 06:52 UTC, petschki approved these changes, later dismissed
I've fixed the link to patternslib. I'd say its good to merge.

2024-07-01 09:50 UTC, stevepiercy submitted a review, later dismissed
I'll merge when green, excluding linkcheck failures.

2024-07-01 09:53 UTC, petschki commented
@stevepiercy regarding casing: on the webpack docs its called "Module Federation" everywhere ... https://webpack.js.org/concepts/module-federation/ ...

2024-07-01 10:05 UTC, stevepiercy commented
@petschki reverted in [9a80b1b](https://github.com/plone/documentation/pull/1253/commits/9a80b1b3f4eef2ee0d4560cd3f6bb3b10ee01428). Why, webpack, _why_? Especially when you don't even use title case for your own name! 🙄 

@ksuess you still have requested changes in your review, but I think all your questions were answered, so I'm going to merge this. If not, then would you please open a new issue? Thank you!

2024-07-01 10:10 UTC, merged