add documentation for switching color themes
plone/documentation pull request #1443
Opened 2023-02-09 15:16 UTC by toalba

2023-02-25 14:19 UTC, stevepiercy submitted a review, later dismissed
I approve, but I would like @MrTango or another content expert from the Classic UI team to review.

If we don't hear back within a week, please ping me to remind me, and I'll go ahead and merge this. Thank you!

2023-02-27 06:25 UTC, petschki requested changes
Documentation is good, but it's based on the not yet released barceloneta/mockup/staticresources versions introducing Bootstrap 5.3 ... we agreed at the alpine city sprint to release this as minor feature versions (semantic) and ship it with Plone 6.1 but you can use those versions also in Plone 6.0 ... @toalba it would be good to mention this in the docs somewhere.

2023-02-27 08:17 UTC, MrTango approved these changes, later dismissed
what petschki says ;)

2023-02-27 10:00 UTC, stevepiercy requested changes
A couple more corrections that I missed on my first pass, and addition of a `versionadded`.

I also asked a couple of questions, as a couple of things are not clear to me. Thank you!

2023-02-27 10:00 UTC, stevepiercy commented on docs/classic-ui/theming/color-mode.md
> +    <input type="email" class="form-control" id="exampldescribtioneInputEmail1" aria-describedby="emailHelp">
What happened here? Did you mean `exampleDescriptionInputEmail1`?

2023-02-27 10:00 UTC, stevepiercy commented on docs/classic-ui/theming/color-mode.md
> +This chapter is a guide for how to implement color themes in Plone 6.1.
````suggestion
This chapter is a guide for how to implement color modes in Plone 6.1.

```{versionadded} Plone 6.1
```

````

2023-02-27 10:00 UTC, stevepiercy commented on docs/classic-ui/theming/color-mode.md
>  Bootstrap 5.3 has introduced [Color Modes](https://getbootstrap.com/docs/5.3/customize/color-modes/).
```suggestion
Bootstrap 5.3 has introduced [color modes](https://getbootstrap.com/docs/5.3/customize/color-modes/).
```

2023-02-27 10:00 UTC, stevepiercy commented on docs/classic-ui/theming/color-mode.md
> +There is also the possibility to use the color modes in Plone 6.0 by manually include `barceloneta=3.1.0` and `plone.staticresources=2.1.0`.
Manually include... where? `requirements.txt`? Please be explicit.

```suggestion
To use color modes in Plone 6.0, manually include `barceloneta=3.1.0` and `plone.staticresources=2.1.0`, as described in {ref}`pin-the-version-of-an-add-on`.
```

2023-02-27 10:14 UTC, toalba commented on docs/classic-ui/theming/color-mode.md
> +There is also the possibility to use the color modes in Plone 6.0 by manually include `barceloneta=3.1.0` and `plone.staticresources=2.1.0`.
You right i will add it. Adding the version binding to the `requirements.txt` will do it. If working with mxdev you can add it to the mx.ini, but i think this information is to explicit right? @stevepiercy

2023-02-27 10:20 UTC, toalba commented on docs/classic-ui/theming/color-mode.md
> +    <input type="email" class="form-control" id="exampldescribtioneInputEmail1" aria-describedby="emailHelp">
This is just a example on using the `data-bs-theme` attribute on a from. I don't know it the difference of id="exampleInputEmail1" and id="exampldescribtioneInputEmail1" is important, but i am new to docs so if you say, i add it.

2023-02-27 10:31 UTC, stevepiercy commented on docs/classic-ui/theming/color-mode.md
> +There is also the possibility to use the color modes in Plone 6.0 by manually include `barceloneta=3.1.0` and `plone.staticresources=2.1.0`.
@toalba OK, I think I understand now. I updated my suggestion with a MyST reference to https://6.docs.plone.org/install/manage-add-ons-packages.html#pin-the-version-of-an-add-on. Let's check the build or preview to make sure it renders correctly.

2023-02-27 10:33 UTC, stevepiercy commented on docs/classic-ui/theming/color-mode.md
> +    <input type="email" class="form-control" id="exampldescribtioneInputEmail1" aria-describedby="emailHelp">
`exampldescribtioneInputEmail1` looks like a typographical mistake to me. That's why I asked. I think the original `exampleInputEmail1` is descriptive enough.

2023-02-27 10:36 UTC, toalba commented on docs/classic-ui/theming/color-mode.md
> +There is also the possibility to use the color modes in Plone 6.0 by manually include `barceloneta=3.1.0` and `plone.staticresources=2.1.0`.
ah ok, thanks

2023-02-27 10:53 UTC, toalba commented on docs/classic-ui/theming/color-mode.md
> +There is also the possibility to use the color modes in Plone 6.0 by manually include `barceloneta=3.1.0` and `plone.staticresources=2.1.0`.
The Reference is not showing in the preview, this is unknown terrain for me. can you look? @stevepiercy

2023-02-27 11:52 UTC, stevepiercy requested changes

2023-02-27 11:52 UTC, stevepiercy commented on docs/classic-ui/theming/color-mode.md
> +To use color modes in Plone 6.0, manually include `barceloneta=3.1.0` and `plone.staticresources=2.1.0`, as described in {ref}`pin-the-version-of-an-add-on`.
My apologies, I gave you the incorrect reference. This time I looked it up in the source.

```suggestion
To use color modes in Plone 6.0, manually include `barceloneta=3.1.0` and `plone.staticresources=2.1.0`, as described in {ref}`manage-add-an-add-on`.
```

2023-02-27 12:00 UTC, stevepiercy approved these changes
Let's wait for a green build, and ensure that the preview looks correct https://deploy-preview-1443--6-docs-plone-org.netlify.app/classic-ui/theming/color-mode.html

I'm OK with merging this now. Yes, it's premature, but the momentum is here, and the versioning issue has been addressed adequately, so I'll go with it. We need docs badly.

@petschki @MrTango any last thoughts?

2023-02-27 12:03 UTC, petschki approved these changes
Nice! Thanks @toalba !

2023-02-27 12:07 UTC, toalba commented
Thanks as well to @lenadax , who initially developed these feature.

2023-02-27 12:26 UTC, merged

2023-02-28 16:33 UTC, rnixx commented
Then it's time to drop alpha releases of mockup, staticresources and barceloneta including bs 5.3 i guess ;)