Add and link glossary terms UID and intid
plone/documentation pull request #1466
Opened 2023-03-14 08:25 UTC by lord2anil

glossary added for UID and intid.
 closes #1460

2023-03-14 09:12 UTC, stevepiercy requested changes
Please see review comments. Thank you!

2023-03-14 09:12 UTC, stevepiercy commented on docs/glossary.md
> +UID
We can stack terms.

```suggestion
unique identifier
UID
```

2023-03-14 09:12 UTC, stevepiercy commented on docs/glossary.md
> +   UID is an abbreviation meaning "User Identifier." On a Unix-like operating system, it is a unique numerical identifier assigned to each user. The system uses the UID to identify the user and deter
In this context, we are assigning a unique identifier to an image object, which is independent of a user identifier.

```suggestion
   UID is an acronym meaning "unique identifier".
   A UID is an identifier that is guaranteed to be unique among all identifiers used for those objects and for a specific purpose.
```

2023-03-14 09:12 UTC, stevepiercy commented on docs/glossary.md
> +intid
Where's the linked term?

2023-03-14 09:12 UTC, stevepiercy commented on docs/glossary.md
> +intid
```suggestion
integer identifier
intid
```

2023-03-14 09:12 UTC, stevepiercy commented on docs/glossary.md
> +    In Plone, a "intid" is an integer identifier that is used to uniquely identify content objects within a Plone site. Each content item in a Plone site is given a unique intid, which the system use
```suggestion
    In Plone, an integer identifier, or intid, is used to uniquely identify content objects within a Plone site.
    Each content item in a Plone site is given a unique intid, which the system uses internally to monitor and manage content.
```

2023-03-14 09:23 UTC, jensens commented on docs/glossary.md
> +    In Plone, a "intid" is an integer identifier that is used to uniquely identify content objects within a Plone site. Each content item in a Plone site is given a unique intid, which the system use
"monitor and manage content"? 
I would say: reference content, manage link-integrity, manage translations and related.

2023-03-14 09:48 UTC, stevepiercy approved these changes
I approve, assuming that you will incorporate @jensens's suggestions as well. Thank you!

2023-04-08 23:10 UTC, stevepiercy commented
@lord2anil would you please update this PR? Thank you!

2023-04-09 04:40 UTC, stevepiercy requested changes
I think this is what @jensens intended, can you verify?

Also please resolve conflicts in the file `docs/glossary.md`. This PR cannot be merged until that is done. Thank you!

2023-04-09 04:40 UTC, stevepiercy commented on docs/glossary.md
> +    Each content item in a Plone site is given a unique intid, which the system uses internally to monitor and manage content.
Per @jensens's comment.

```suggestion
    Each content item in a Plone site is given a unique intid, which the system uses internally to reference content, keep track of link-integrity, link translations, and other related purposes.
```

2023-04-09 05:20 UTC, lord2anil commented
i don't have write access to branch .The created a new PR form  Fork repo please have a look. https://github.com/plone/documentation/pull/1487/#issue-1659752403

2023-04-09 06:38 UTC, stevepiercy commented
Ah, sorry, that's right, we had to restrict access to new contributors. There was an announcement in the Community Forum, and we documented details in [First-time contributors](https://6.docs.plone.org/contributing/first-time.html). Closing this PR in favor of #1487.

2023-04-09 06:38 UTC, closed without merging