Container examples with traefik
plone/documentation pull request #1501
Opened 2023-05-20 11:11 UTC by margaridasp

Fixes #1500 

I think we still need to create simpler examples with less components.

2023-05-25 13:20 UTC, ericof approved these changes

2023-05-25 13:21 UTC, ericof commented
@margaridasp Let's merge this one, then create other examples :-)

2023-05-26 09:45 UTC, stevepiercy requested changes
Minor suggestions for proper names, renaming headings, MyST syntax for files.

2023-05-26 09:45 UTC, stevepiercy commented on docs/glossary.md
> +traefik
This is a proper name and there are many products under the Traefik brand name. We should be explicit to disambiguate it from all their other products.

`Traefik` should also be added to https://github.com/plone/documentation/blob/6.0/styles/Vocab/Plone/accept.txt

```suggestion
Traefik Proxy
```

2023-05-26 09:45 UTC, stevepiercy commented on docs/glossary.md
> +    [traefik](https://traefik.io/) is an open-source reverse proxy and load balancer, suitable for containerized architectures.
```suggestion
    [Traefik Proxy](https://traefik.io/traefik/) is an open-source reverse proxy and load balancer, suitable for containerized architectures.
```

2023-05-26 09:45 UTC, stevepiercy commented on docs/install/containers/examples/traefik-volto-plone-varnish.md
> +    "property=og:title": "traefik, Frontend, Backend, Varnish container example"
```suggestion
    "property=og:title": "Traefik Proxy, Frontend, Backend, Varnish container example"
```

2023-05-26 09:45 UTC, stevepiercy commented on docs/install/containers/examples/traefik-volto-plone-varnish.md
> +    "keywords": "Plone 6, Container, Docker, traefik, Frontend, Backend, Varnish"
```suggestion
    "keywords": "Plone 6, Container, Docker, Traefik Proxy, Frontend, Backend, Varnish"
```

2023-05-26 09:45 UTC, stevepiercy commented on docs/install/containers/examples/traefik-volto-plone-varnish.md
> +# traefik, Frontend, Backend, Varnish container example
```suggestion
# Traefik Proxy, Frontend, Backend, Varnish container example
```

2023-05-26 09:45 UTC, stevepiercy commented on docs/install/containers/examples/traefik-volto-plone-varnish.md
> +{term}`traefik` in this example is used as a reverse proxy.
```suggestion
{term}`Traefik Proxy` in this example is used as a reverse proxy.
```

2023-05-26 09:45 UTC, stevepiercy commented on docs/install/containers/examples/traefik-volto-plone-varnish.md
> +### Varnish configuration
Let's promote it one level.

```suggestion
## Varnish configuration
```

2023-05-26 09:45 UTC, stevepiercy commented on docs/install/containers/examples/traefik-volto-plone-varnish.md
> +## Setup
This is not really "setup".

```suggestion
## Create a project space
```

2023-05-26 09:45 UTC, stevepiercy commented on docs/install/containers/examples/traefik-volto-plone-varnish.md
> +### Service configuration with Docker Compose
Let's promote this one level, too.

```suggestion
## Service configuration with Docker Compose
```

2023-05-26 09:45 UTC, stevepiercy commented on docs/install/containers/examples/traefik-volto-plone-varnish.md
> +Now let's create a `docker-compose.yml` file:
```suggestion
Now let's create a {file}`docker-compose.yml` file:
```

2023-05-26 09:45 UTC, stevepiercy commented on docs/install/containers/examples/traefik-volto-plone-varnish.md
> +Add there a `varnish.vcl` that will be used by the varnish image:
```suggestion
Add there a file {file}`varnish.vcl` that will be used by the Varnish image:
```

2023-05-26 09:51 UTC, stevepiercy commented
It is safe to ignore the failing docs build. I have another PR open that fixes the redirect in https://github.com/plone/documentation/pull/1504

2023-05-26 17:46 UTC, ericof commented
@stevepiercy We can merge this whenever you are ready :-)

2023-05-26 19:12 UTC, stevepiercy approved these changes
Thank you! I love me some tasty docs!

2023-05-26 19:12 UTC, merged