Barceloneta based Classic UI theme
plone/documentation pull request #1516
Opened 2023-07-03 04:36 UTC by petschki

2023-07-11 12:53 UTC, gogobd commented
Hi, @petschki !

* Maybe consider mentioning the version of npm you would recommend and that the generated theme addon needs to be installen (via Plone Panel).

Please mention that the file that should contain the font definitions is `_variables.scss`. I used a font other than the default font just to be able to see the change immediately:

```
$font-family-sans-serif:                    "Papyrus", "Fantasy";
$font-family-condensed:                     "Papyrus", "Fantasy"; //just on toolbar
$font-family-serif:                         "Papyrus", "Fantasy";
```

* This `$enabled-rounded: false;` switch didn't work.

* I was assuming that the changes mentioned in "Maps" would go into `maps.scss`, it's not mentioned but at the same time quite obvious i.e. most likely everyone's first guess.

2023-07-11 23:59 UTC, stevepiercy commented
I just did a merge commit to bring it inline with `main` due to the failing docs test. We will see if it passes now.

2023-07-12 06:00 UTC, stevepiercy requested changes
Mostly a bunch of MyST, style guide, and English syntax and grammar fixes.

Would you please take a look at moving Node.js and nvm installation to the top of the page after the introduction, and see if there is something that can be reused from existing installation documentation? Thank you!

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +After that the theming structure is setup and ready for customization.
```suggestion
After that the theming structure is set up and ready for customization.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +```
````suggestion
```text
````

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +
Let's convert this into a more compact definition list, instead of a bunch of headings with sections, which will also make it more a part of the current section. If a definition has more than one sentence, then indent them to align with the start of the first sentence. Example:

```
`index.html`
:   Basic HTML structure for the site layout.

`manifest.cfg`
:   Basic theme configuration for the backend.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +Then change the working directory into the created package and add the
Please use one sentence per line. Docs are not code. This makes it easier to review and make suggestions, if needed, and avoids the need to rewrap if it gets edited.

```suggestion
Then change the working directory into the created package and add the basic theme structure with the following command.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +basic theme structure with:
```suggestion
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +-   Diazo rules which translate the `index.html` and fills it with content
```suggestion
-   Diazo rules which translate the `index.html` and fill it with content from the backend.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +    from the backend.
```suggestion
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +-   Override Bootstrap and/or Barceloneta variables here.
```suggestion
-   Override Bootstrap and Barceloneta variables here.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +-   Base theme file which follows "Option B" of customizing Bootstrap imports
```suggestion
-   Base theme file which follows "Option B" of customizing Bootstrap imports to enable injections of custom variables and maps.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +    to enable custom variable and map injections. Note that the order of these imports is mandatory to ensure overriding the defaults. See https://getbootstrap.com/docs/5.3/customize/sass/#importing
```suggestion
    Note that the order of these imports is mandatory to ensure overriding the defaults.
    See https://getbootstrap.com/docs/5.3/customize/sass/#importing.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +To compile the SCSS code you have to install Node.js (v16+) and the required dependencies with `npm`. Then run the package script `build` inside the `theme/` folder:
One sentence per line.
```suggestion
To compile the SCSS code you have to install Node.js (v16+) and the required dependencies with `npm`.
Then run the package script `build` inside the `theme/` folder:
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +the `scss/` folder.
Does this also allow the developer to preview their changes in the browser? If so, please mention it.

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +
```suggestion


(classic-ui-theming-barceloneta-compiling-theme-resources-label)=

## Compiling theme resources

```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +```
````suggestion
```text
````

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +### SCSS and root variables
```suggestion

(classic-ui-theming-barceloneta-scss-and-root-variables-label)=

### SCSS and root variables
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +To set a custom font you define the font variables in `scss/_variables.scss`:
```suggestion
To set a custom font, you define the font variables in `scss/_variables.scss`:
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +This will override the default values from barceloneta.
```suggestion
This will override the default values from Barceloneta.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +Same procedure if you want to disable rounded corners for borders:
```suggestion
The following example shows how to disable rounded corners for borders.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +### Maps
```suggestion


(classic-ui-theming-barceloneta-maps-label)=

### Maps
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +Maps are key value pairs to make CSS generation easier. As an example this is the workflow colors map:
```suggestion
Maps are key/value pairs to make CSS generation easier.
As an example, the following example shows the workflow colors map:
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +If you have a custom workflow state you can add your state color to the default map. Just add the following to `scss/_maps.scss`:
```suggestion
If you have a custom workflow state, you can add your state color to the default map in `scss/_maps.scss` as shown below.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +### Custom CSS code
```suggestion

(classic-ui-theming-barceloneta-custom-css-code-label)=

### Custom CSS code
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +Inside the file `theme/_custom.scss` you can write all your custom CSS/Sass code
```suggestion
Inside the file `theme/_custom.scss`, you can write all your custom CSS/Sass code to adapt the theme to your needs.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +to adapt the theme to your needs. Feel free to add more files inside the `scss/` folder to make your code more readable. Don't forget to import your custom files in `scss/theme.scss`.
```suggestion
Feel free to add more files inside the `scss/` folder to make your code more readable.
Don't forget to import your custom files in `scss/theme.scss`.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +(classic-ui-theming-barceloneta-default-variables-properties-label)=
```suggestion
(classic-ui-theming-barceloneta-default-variables-and-properties-label)=
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +A complete list of all properties see {ref}`classic-ui-theming-barceloneta-default-variables-properties-label`.
```suggestion
A complete list of all properties see {ref}`classic-ui-theming-barceloneta-default-variables-and-properties-label`.
```

2023-07-12 06:00 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +### Properties
To avoid duplicate heading at the end of the file.

```suggestion
### SCSS and properties
```

2023-07-12 08:37 UTC, petschki commented
@stevepiercy thank you for your review. I've changed the doc and put the Node.js information at the top  with a link to `Install Plone from its packages`. There I've found details on installing python, node, nvm ...

2023-07-12 09:23 UTC, stevepiercy approved these changes
I decided it would be easier to push a commit 63b366081be99085dae68e3e5f2d7d8208930e51 with my suggestions than go through a formal review. Feel free to change them. Thank you for your contribution. This is super helpful.

2023-07-12 09:23 UTC, stevepiercy commented on docs/classic-ui/theming/barceloneta.md
> +## Create a Classic UI theme addon package
```suggestion
## Create a Classic UI theme add-on package
```

2023-07-12 13:55 UTC, petschki commented
This is good to merge for me 🤗 @gogobd wanted to take a second look over this.

2023-07-13 08:24 UTC, merged