Nuclia Workflow Designed
plone/documentation pull request #1521
Opened 2023-07-25 07:10 UTC by justdaksh

1. Implemented `upload.py` 
2. Drafted `workflow` for the same
Additional context- https://github.com/collective/plone-nuclia/issues/3
cc: @stevepiercy @ebrehault @fredvd

2023-07-25 08:03 UTC, stevepiercy requested changes
Looks good, except for the submodule commit. That needs to be removed from this PR. Thank you!

2023-07-25 08:03 UTC, stevepiercy commented on submodules/volto
This file should not be committed to the repo. I do that upon a release of docs.

2023-07-26 20:42 UTC, stevepiercy requested changes
A tiny style preference, then this is good to merge.

2023-07-26 20:42 UTC, stevepiercy commented on .github/workflows/nuclia_sync.yml
> +    - name: Run Nuclia Sync
Let's use consistent spacing between `name`s. I think a blank line between each pair is helpful to see each task.

2023-07-28 07:54 UTC, stevepiercy approved these changes
This looks good.

2023-08-02 06:24 UTC, justdaksh commented
@stevepiercy Going ahead with the merge.

2023-08-02 06:24 UTC, merged

2023-08-02 06:47 UTC, stevepiercy commented
Woo-hoo! Thanks for verifying that you have sufficient permission. Next let's poke @fredvd to see what he needs from you to establish a staging server.