Add Viewlets section to 6.0 backend upgrade guide.
plone/documentation pull request #1633
Opened 2024-02-29 17:21 UTC by mauritsvanrees

## Issue number

- Fixes https://github.com/plone/Products.CMFPlone/issues/3911

## Description

This adds a section to the upgrade guide from Plone 5.2 to 6.0 for the backend.  It documents the changes and moves of viewlets.

I have added a table, but really it is too wide: it partially falls behind the table of contents.  I wonder if something can be done about that.

2024-02-29 20:37 UTC, mauritsvanrees commented
Exact preview link:
https://deploy-preview-1633--6-docs-plone-org.netlify.app/backend/upgrading/version-specific-migration/upgrade-to-60.html#viewlets

2024-02-29 23:43 UTC, stevepiercy requested changes
Minor English and MyST syntax, and a question.

2024-02-29 23:43 UTC, stevepiercy commented on docs/backend/upgrading/version-specific-migration/upgrade-to-60.md
> +The reason for renaming, is that some viewlet names contained the name of a viewlet manager.
```suggestion
This is because some viewlet names contained the name of a viewlet manager.
```

2024-02-29 23:43 UTC, stevepiercy commented on docs/backend/upgrading/version-specific-migration/upgrade-to-60.md
> +Plone 6.0 removes such references from the viewlet names, to avoid confusion.
```suggestion
Plone 6.0 removes such references from the viewlet names to avoid confusion.
```

2024-02-29 23:43 UTC, stevepiercy commented on docs/backend/upgrading/version-specific-migration/upgrade-to-60.md
> +- Plone 6.0 removes the `plone.documentactions (IDocumentActions)`  viewlet manager. In Plone 5.2 it was already empty.
```suggestion
- Plone 6.0 removes the `plone.documentactions (IDocumentActions)` viewlet manager. In Plone 5.2 it was already empty.
```

2024-02-29 23:43 UTC, stevepiercy commented on docs/backend/upgrading/version-specific-migration/upgrade-to-60.md
> +- Plone 6.0 renames the `plone.belowcontenttitle.documentbyline` viewlet to `plone.documentbyline` . It remains in manager `plone.belowcontenttitle`.
```suggestion
- Plone 6.0 renames the `plone.belowcontenttitle.documentbyline` viewlet to `plone.documentbyline`. It remains in manager `plone.belowcontenttitle`.
```

2024-02-29 23:43 UTC, stevepiercy commented on docs/backend/upgrading/version-specific-migration/upgrade-to-60.md
> +:::{table} Viewlet changes from 5.2 to 6.0
This gets rendered as a caption beneath the table instead of above it, and its syntax is strange with only an opening code fence of 3 colons. What was your intent with this directive?

````suggestion
```{table} Viewlet changes from 5.2 to 6.0
````

...and after the table, then close it with another code fence of three backticks ` ``` `.

2024-02-29 23:43 UTC, stevepiercy commented on docs/backend/upgrading/version-specific-migration/upgrade-to-60.md
> +You can toggle navigation to make more of the table visible.
FYI, this is fixed upstream in https://pydata-sphinx-theme.readthedocs.io/en/stable/examples/kitchen-sink/tables.html#giant-tables, allowing horizontal scrolling of the content.

2024-02-29 23:43 UTC, stevepiercy commented on docs/backend/upgrading/version-specific-migration/upgrade-to-60.md
> +- Plone 6.0 moves the `plone.footer` viewlet from `plone.app.layout/viewlets` to `plone.app.portlets`. The viewlet remains in manager `plone.portalfooter`. It renders the portlets from the `plone.foo
This line was omitted from the table, but it is not obvious to me how it can fit in it.

2024-02-29 23:43 UTC, stevepiercy commented on docs/backend/upgrading/version-specific-migration/upgrade-to-60.md
> +| | `plone.belowcontentbody` | `plone.rights` | `plone.belowcontentbody` |
````suggestion
| | `plone.belowcontentbody` | `plone.rights` | `plone.belowcontentbody` |
```
````

2024-03-07 11:04 UTC, stevepiercy commented
@mauritsvanrees I pushed some commits to get this over the finish line. I have a question about one item in my earlier review.

Also, to make the table display within a narrow viewport, what do you think about removing `plone.` from all of the values in the table, and make a note, such as:

```
The names in the following table have had the namespace `plone.` removed from them for display purposes only.
In your code, you should use the object's `plone.` namespace as a prefix.
```

Please let me know. Thank you!

2024-03-07 11:45 UTC, mauritsvanrees commented on docs/backend/upgrading/version-specific-migration/upgrade-to-60.md
> +- Plone 6.0 moves the `plone.footer` viewlet from `plone.app.layout/viewlets` to `plone.app.portlets`. The viewlet remains in manager `plone.portalfooter`. It renders the portlets from the `plone.foo
I say that the table shows the same information, but indeed for this line it is not true.

I will move this line below the table, let's see if that is better.

2024-03-07 11:58 UTC, mauritsvanrees commented
> @mauritsvanrees I pushed some commits to get this over the finish line. I have a question about one item in my earlier review.

@stevepiercy  Thanks.  I did not have time till today to look at it again.  Now I followed up.

> Also, to make the table display within a narrow viewport, what do you think about removing `plone.` from all of the values in the table, and make a note, such as:

Agreed, that seems better.  I have pushed the changes.

Optionally, we could leave the first two content rows of the table out, and move the corresponding first two bullet points below it.  Let me add this as screen shot to compare:

![Screenshot 2024-03-07 at 12 54 14](https://github.com/plone/documentation/assets/210587/120f76f8-5835-43c3-9d5a-674e59a08407)

We could also have the table contain only the viewlets that have changed or moved.  The two lines with an empty cell for the 6.0 viewlet would then be gone.
Many possibilities. But maybe the big table is fine anyway.

2024-03-07 12:10 UTC, stevepiercy commented
> Optionally, we could leave the first two content rows of the table out, and move the corresponding first two bullet points below it.

I like that much better. It would also mean that the table fits in the viewport, and you could remove that sentence mentioning that you can hide the local navigation to view more of the table.

2024-03-07 13:21 UTC, mauritsvanrees commented
> > Optionally, we could leave the first two content rows of the table out, and move the corresponding first two bullet points below it.
> 
> I like that much better. It would also mean that the table fits in the viewport, and you could remove that sentence mentioning that you can hide the local navigation to view more of the table.

Done.

2024-03-07 13:53 UTC, stevepiercy approved these changes
Thank you!

2024-03-07 13:53 UTC, merged