update package deps mental model to reflect 6.1
plone/documentation pull request #1665
Opened 2024-05-15 12:05 UTC by jensens

This targets 6.1

2024-05-15 22:04 UTC, stevepiercy requested changes
Reminder that docs in `/coredev` are not yet deployed in Production, and need to be migrated. See https://github.com/plone/buildout.coredev/issues/840#issuecomment-1441479383 for latest status.

Also I wonder if using Graphviz for the model instead of ASCII art might be visually more appealing, although more difficult to create if you don't know its syntax? I know that @MrTango created one simple Graphviz element in https://6.docs.plone.org/classic-ui/views.html. I don't have that knowledge beyond what is in the docs now.

2024-05-15 22:04 UTC, stevepiercy commented on coredev/packages-dependencies.md
> +│ Core-Addons                │
```suggestion
│ Core add-ons:               │
```

2024-05-15 22:04 UTC, stevepiercy commented on coredev/packages-dependencies.md
> +│ Core-APIs                  │
```suggestion
│ Core APIs:                 │
```

2024-05-15 22:04 UTC, stevepiercy commented on coredev/packages-dependencies.md
> +│ The space between (core )  │
"The space between (core )"? Between what two things?

2024-05-16 05:56 UTC, jensens commented
> Also I wonder if using Graphviz for the model instead of ASCII art might be visually more appealing, although more difficult to create if you don't know its syntax?

I would prefer mermaid - do we support it? Sphinx at least has a plugin I used in other projects already.

2024-05-16 07:16 UTC, stevepiercy commented
> I would prefer Mermaid - do we support it?

We most certainly could! The only reason it is not currently supported is because no one has asked for it until now. 😁 

That `:zoom:` option is nifty.

https://pypi.org/project/sphinxcontrib-mermaid/

2024-06-28 01:06 UTC, stevepiercy commented
@jensens I'm going to close this in favor of https://github.com/plone/documentation/pull/1671/, where you can insert a Mermaid diagram in docs at https://github.com/plone/documentation/pull/1671/files#diff-36199f263c1ec44ec26fc136ea22e39344bf44acc065e03e0fe26bc263d2f9f2 that will be published soon. The last step in that PR will be to purge the files at the root in `coredev`.

I already added support to the docs [`conf.py` in that PR](https://github.com/plone/documentation/pull/1671/files#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3) in anticipation. Please let me know. Thank you!

2024-06-28 01:06 UTC, closed without merging