add notes to create an emergency user
plone/documentation pull request #1703
Opened 2024-09-12 18:59 UTC by 1letter

i created a subdirectory for users and groups and add a file with a short description to create an emergency user in a pip and buildout based installation of Plone.

2024-09-12 19:11 UTC, 1letter commented
@stevepiercy can you check wording and spelling please?

2024-09-13 10:06 UTC, stevepiercy requested changes
I merged content from Plone 5 documentation, and added an introduction for each scenario.

There was one sentence remaining that confuses me. Please see my review comment. Thank you!

2024-09-13 10:06 UTC, stevepiercy commented on docs/backend/users-groups/emergency-user.md
> +First of all, do the following steps not in a production environment!
What would someone do in a Production environment? Are they out of luck?

2024-09-13 10:17 UTC, stevepiercy commented
Here are direct links to the RTD pull request preview:

- https://plone6--1703.org.readthedocs.build/backend/users-groups/index.html
- https://plone6--1703.org.readthedocs.build/backend/users-groups/emergency-user.html

2024-09-13 10:39 UTC, stevepiercy commented
The failing linkcheck for Docker Linux install can be ignored, as I fixed it in https://github.com/plone/documentation/pull/1704.

@robgietema for https://nickcms.org, can you check its status? linkcheck says it is not responding. Alternatively, should I use https://docs.nickcms.org/ or https://github.com/robgietema/nick? Please advise.

2024-09-13 11:22 UTC, 1letter commented on docs/backend/users-groups/emergency-user.md
> +First of all, do the following steps not in a production environment!
Of course, you can do this operations in a production env, but you should not do this. ;-)

2024-09-13 11:36 UTC, stevepiercy commented on docs/backend/users-groups/emergency-user.md
> +First of all, do the following steps not in a production environment!
What should someone do in production instead? We can't say "don't do this", then in the next section say "do this". It's very confusing.

Perhaps you can include what are the consequences and risks of doing this in production, aside from the obvious, specifically that the site will be down while adding the emergency user.

2024-09-14 21:17 UTC, davisagli commented on docs/backend/users-groups/emergency-user.md
> +```
Why? This is only necessary if the site uses a ZODB filestorage directly without using ZEO or Relstorage (then the storage is locked and can't be accessed by multiple processes at once).

2024-09-14 21:17 UTC, davisagli commented on docs/backend/users-groups/emergency-user.md
> +./venv/bin/instance start
This assumes that Plone was installed into a Python virtualenv in the `venv` directory. That may or may not be the case.

It also assumes there is a script named `instance`, which is not usually the case when Plone was installed using pip.

2024-09-14 21:17 UTC, davisagli commented on docs/backend/users-groups/emergency-user.md
> +```
This assumes the buildout includes a `plone.recipe.zope2instance` section named `instance`. That may or may not be the case.

2024-11-06 09:21 UTC, stevepiercy commented on docs/backend/users-groups/emergency-user.md
> +First of all, do the following steps not in a production environment!
@1letter can you answer the following questions? I want to move this PR forward.

1. What should someone do in production instead?
2. If someone does this in production, what are the risks?
3. In which environments is it OK to do this?

2024-11-06 09:22 UTC, stevepiercy commented
@1letter would you please respond to @davisagli's suggestions?

Let's get this finished and published!

2024-11-06 17:17 UTC, davisagli requested changes

2024-11-06 17:17 UTC, davisagli commented on docs/backend/users-groups/emergency-user.md
This should now go in docs/admin-guide and be linked under the "Operate" heading of https://6.docs.plone.org/admin-guide/index.html

2025-02-12 09:47 UTC, ale-rt commented on docs/backend/users-groups/emergency-user.md
By mistake I added https://github.com/plone/documentation/pull/1851

2025-02-12 14:02 UTC, ale-rt commented on docs/backend/users-groups/emergency-user.md
> +First of all, do the following steps not in a production environment!
I think I addressed these issues with #1854 

I decided to talk about "Zope Manager Users", which IMO it is more appropriate than "Emergency users"
I added a note about taking in to account the security implication of adding a Zope manager user.

2025-02-12 14:03 UTC, ale-rt commented
> Here are direct links to the RTD pull request preview:
> 
> * https://plone6--1703.org.readthedocs.build/backend/users-groups/index.html
> * https://plone6--1703.org.readthedocs.build/backend/users-groups/emergency-user.html

Those are now:

- https://plone6--1703.org.readthedocs.build/admin-guide/index.html
- https://plone6--1703.org.readthedocs.build/admin-guide/add-emergency-user.html

2025-02-12 14:04 UTC, ale-rt commented on docs/backend/users-groups/emergency-user.md
> +```
I added a note about that

2025-02-12 14:05 UTC, ale-rt commented on docs/backend/users-groups/emergency-user.md
> +./venv/bin/instance start
I added a note about that

2025-02-12 14:05 UTC, ale-rt commented on docs/backend/users-groups/emergency-user.md
> +```
I added a note about that

2025-02-12 14:06 UTC, ale-rt commented on docs/backend/users-groups/emergency-user.md
I closed #1851 and merged it with this one by taking care of @davisagli notes. I would consider this one to be ready for another review cycle.

2025-02-13 13:19 UTC, acsr commented on docs/backend/users-groups/emergency-user.md
> +First of all, do the following steps not in a production environment!
@ale-rt @stevepiercy I like the change to extend the scope to "Zope Manager Users" and mention the "Emergency user", but the traditional term "Emergency user" should be highlighted in the text to reflect the purpose in production!

I added this here, because of the context of the suggestion by @stevepiercy in my discussions with him and seperately with @jensens.

But it needs to be seen also in context of the current preview:
https://plone6--1703.org.readthedocs.build/admin-guide/add-emergency-user.html

## I would also enhance two things:

### 1. Do not tag admin:admin  "as usual":
It is OK to use that for an instance fired up for testing and to be destroyed at once or soon or later before going to production. But it should be mentioned and made clear that for instances installed ending in production the password should be changed before anything goes into persistence. The consequences might be not obvious, but even behind a proxy the ZMI root may be reachable (like with Volto) and can lead to a permanent backdoor not easy to discover even not using admin:admin.

Imagine a different user:password than admin/admin and the sysadmin / integrator changes and the httpauth in the ZMI backend is not changed or restored from a backup. Then an in fact unauthorízed person can try to gain access with these hardcoded credentials.

### 2. So there should be a prominent warning to immediately change these credentials and pack the database before going into production. 

## Further considerations

### 3. @1letter completely denied to use this in production. I am contrary because the emergency user purpose is still valid for emergency use cases like changed admins or lost credentials. The Challenge in production is, that the user is persistent in the database and therefore also in backups. So old backups are still accessible with the old credentials when restored without proper awareness and documentation of changes in access credentials including point in time.

### 4. In the past there was an approach that the installers created a random password and wrote it into the filesystem when the initial password was not specified during install.

When you removed the file, took a note in your password manager and changed the password at once no traces were left. Today these ways are deeply buried in e.g. docker containers and not easy to handle.

## ongoing work on this
I am working on writing this up for cookieplone based docker deployments, but it is too early and would block the release of this PR. This can be added later.

2025-02-13 14:27 UTC, acsr commented
@stevepiercy I dump this here until final decision where to put this

## [[Draft]] Emergency User Creation in dockerized setup
I can confirm that the following procedure works for me on a running docker swarm instance for the full featured docker based Plone Volto deployment created by current Cookieplone project template including postgres, traefik, varnish:

### How to create a new `Zope Manager User` with a non existing user-ID
1. Enter the host via ssh as root
2. list the running containers: `docker ps`
3. enter a shell in the first backend container listed: `docker exec -it [[4-digitPartOfID]] bash`
4. run command in the app folder: `./docker-entrypoint.sh bin/addzopeuser -c /app/etc/relstorage.conf admin3 plone`
5. Response: `User admin3 created`

The user is now available in the ZMI root at at `/acl_users/users/manage_users`
- In Volto use the url `/ClassicUI/aq_parent/acl_users/users/manage_users`

### What I did not test now
- Execute the command in an entrypoint / overlay container with or without running backend / database
Advice is maybe available via @jensens 

### Notes on permissions
- Check permissions in the ZMI root at `/acl_users/manage_access` and search for `admin3`
- In Volto use the url `/ClassicUI/aq_parent/acl_users/manage_access`
- The new user has `Manager` role, but not `Owner` role and no `Take ownership` permission
- You can add the `Owner` role in the ZMI root manually, but only as the original admin user

### Remark on httpauth challenges
The original cookieplone-template project mentioned in my README.md as `Cookieplone (0.8.2)` and `cookiecutter-plone (d9b5293)` included a traefik middleware `mw-backend-auth` in the `docker-compose.yaml` service `backend` Labels section. This httpauth may override the ZMI httpauth. This needs further investigation. A hint how to take this part temporarily out by @jensens is not fully tested. This does not have impact on the Plone Volto login. The new user works there!

2025-02-14 10:43 UTC, ale-rt commented
Note that I would like to rename the file name to match its actual content: https://github.com/plone/documentation/pull/1859

2025-02-14 11:00 UTC, ale-rt commented on docs/backend/users-groups/emergency-user.md
> +First of all, do the following steps not in a production environment!
> The traditional term "Emergency user" should be highlighted in the text to reflect the purpose in production!
> 

Do you have suggestion on how to do that?

> So old backups are still accessible with the old credentials when restored without proper awareness and documentation of changes in access credentials including point in time.

Uhm maybe here I am missing something. When you have access to the DB you can anyway change the password manually there. So I do not consider this a real issues.

> In the past there was an approach that the installers created a random password and wrote it into the filesystem when the initial password was not specified during install.
> 

I think this is extending the scope of this PR. 

> I am working on writing this up for cookieplone based docker deployments, but it is too early and would block the release of this PR. This can be added later.

Agreed!

2025-02-14 11:10 UTC, ale-rt commented
@acsr please check this https://github.com/plone/documentation/pull/1703#discussion_r1955960985, I think that https://github.com/plone/documentation/pull/1860 will better fit your comments.

Anyway I have planned a call with @stevepiercy in a few minutes

2025-02-14 14:16 UTC, acsr commented on docs/backend/users-groups/emergency-user.md
> +First of all, do the following steps not in a production environment!
> So old backups are still accessible with the old credentials when restored without proper awareness and documentation of changes in access credentials including point in time.

@ale-rt The issue in my deployments was in place because the Cookieplone project template sets up a Traefik that creates a basicauth middleware and is created by a label in the docker swarm stack service backend.

In my early attempts I tried to modify the deployment in the docker-compose.yml file, but the changes had no effect and seemed to be ignored in the redeployment.

Today @pbauer, @tlotze and me went through the training docs for the deployment and weeded out lots of pitfalls in order of execution and issues related to images missing on the arm platform for servers.

During these attempts it became clear that the initial modifications during setup were rolled out into the yml file in `devops/stacks/` named after the hostname. Making the changes in this file allows to change the http basicauth of the middleware that overrides the password of the actual ZMI user "admin". Other additional Zope admins or so called "emergengy users" were not affected. The ZMI "admin" users password could be changed successfully in the ZMI but had no effect in this setup behind Traefik. Keep in mind that this user has an ID admin and a seperate name admin that can be changed and should not be mixed up.

That said, the origin of the "persistent" basicauth is discovered and therefore the Cookiplone docs needs to be updated to point to the place for changing that.

2025-02-14 14:44 UTC, acsr commented
See https://github.com/plone/documentation/pull/1703#issuecomment-2656763171

2025-02-14 14:55 UTC, acsr commented
It seems my comment was not saved:
Please reopen this Pull Request after an initial release and we can start to add  add my updated stuff for docker deployments https://github.com/plone/documentation/pull/1703#issuecomment-2656763171

Updated below the mark

2025-02-17 04:06 UTC, davisagli commented on docs/backend/index.md
> +users-groups/index
There is no users-groups/index.md ... I guess this was accidentally left after reorganizing.

```suggestion
```

2025-02-17 04:22 UTC, davisagli approved these changes, later dismissed
LGTM.

We should also add instructions on how to do this in the plone-backend Docker image, based on @acsr's notes -- but this already helps fill the gap and we shouldn't delay merging what is already here.

2025-02-17 10:05 UTC, stevepiercy requested changes
I'll fix the mistaken deletion.

I have another PR https://github.com/plone/documentation/pull/1867 that I will merge into this one, once it is all green.

2025-02-17 10:05 UTC, stevepiercy commented on docs/backend/index.md
> -users-groups
This should not be removed, as it is for managing Plone site Users and Groups in the Users and Groups control panel, but no one has bothered to write its content for Plone 6.

2025-02-17 10:08 UTC, stevepiercy approved these changes
I merged PR #1867.

Once this passes CI, and I double check the PR preview build, I will merge.

2025-02-17 10:09 UTC, stevepiercy commented on docs/backend/index.md
> +users-groups/index
I don't know why `/index` was appended. It needs to be preserved. Done in https://github.com/plone/documentation/pull/1703/commits/45aa742c2350842846853d354621bbc96b2cac6d

2025-02-17 10:13 UTC, merged

2025-02-17 10:13 UTC, stevepiercy commented
@acsr would you please open a new PR with your suggestions? Sorry, I can't make sense of it, as I don't have experience with the situation you describe.

2025-02-18 17:45 UTC, acsr commented
> @acsr would you please open a new PR with your suggestions? Sorry, I can't make sense of it, as I don't have experience with the situation you describe.

Done: https://github.com/plone/documentation/pull/1869