fix: pillow installation for linux
plone/documentation pull request #1805
Opened 2024-12-04 15:11 UTC by Pulkitxm

## Issue number

- Fixes #1084

## Description
- It updates the installation command with `apt install zlib1g-dev libjpeg8-dev`

2024-12-04 15:17 UTC, stevepiercy commented
@Pulkitxm please read and follow https://6.docs.plone.org/contributing/documentation/index.html#granting-permission-to-publish

2024-12-04 15:26 UTC, Pulkitxm commented
I've added the message in PR description, does this aligns with instructions now?

2024-12-04 16:01 UTC, incrhst approved these changes
This looks good

2024-12-05 01:34 UTC, stevepiercy requested changes
This PR also needs the [first sentence of the error message from the community forum](https://community.plone.org/t/plone-installation-failed-in-ubuntu-24-04-1/20201) to be inserted at line 2. This will help people who search for that explicit error message.

`The headers or library files could not be found for jpeg, a required dependency when compiling Pillow from source.`

2024-12-05 06:04 UTC, Pulkitxm commented
@stevepiercy I've made the requested changes, could you please review and confirm?

2024-12-05 07:38 UTC, stevepiercy commented
@Pulkitxm I don't see it. Did you push your commit?

2024-12-05 11:02 UTC, Pulkitxm commented
I have added `The headers or library files could not be found for jpeg, a required dependency when compiling Pillow from source.` in my PR description anything else I have to change?

2024-12-05 12:03 UTC, stevepiercy commented
@Pulkitxm I _still_ don't see it. Did you push your commits?

2024-12-05 12:46 UTC, Pulkitxm commented
![image](https://github.com/user-attachments/assets/e810c2a7-e16f-43ca-9438-4e9de327ba74)

@stevepiercy I am quite confused, I have added the error line in my [pr](https://github.com/plone/documentation/pull/1805) description, what else do I have to do?

2024-12-05 12:51 UTC, stevepiercy commented
@Pulkitxm the change needs to go in Line 2 of the file. Click the Files Changed tab to see what I mean.

2024-12-05 12:57 UTC, Pulkitxm commented
Thanks @stevepiercy, can you take a look now?

2024-12-05 13:14 UTC, stevepiercy approved these changes

2024-12-05 13:25 UTC, stevepiercy commented
@Pulkitxm looks good now. Thank you!

2024-12-05 13:25 UTC, merged