Add docs about how to add custom data attributes
plone/documentation pull request #896
Opened 2017-06-28 14:56 UTC by gforcada

Changes proposed in this pull request:

Today I discovered that one can add its own custom ``data-`` attributes and decided to document it, for everyone's benefit 😄

2017-06-28 14:56 UTC, gforcada commented
@plone/documentation-team if there is a better place where to put this docs, please let me know!

2017-06-28 18:35 UTC, stevepiercy requested changes
Please fix misspelled word

2017-06-28 18:35 UTC, stevepiercy commented on develop/addons/javascript/data-attributes.rst
> +you can create a ZCA adatapter.
adapter

2017-06-28 20:07 UTC, gforcada commented on develop/addons/javascript/data-attributes.rst
> +you can create a ZCA adatapter.
😊 oops!

2017-06-28 20:32 UTC, stevepiercy approved these changes

2017-07-03 11:26 UTC, merged

2017-07-03 11:27 UTC, svx commented
Adjusted and merged !

Thanks !

2017-07-03 11:52 UTC, gforcada commented
@svx thanks for reviewing and merging!!